
package stickynotes;

import javax.swing.JFrame;
import utility.ComponentMover;

/**
 *
 * @author sagar
 */
public class Note extends javax.swing.JFrame {

    // The Sticky Notes Object that created the Note
    protected StickyNotes manager;
    
 
    public Note(StickyNotes manager,String body) {        
        initComponents(); // this should be first ... 
        this.manager = manager;
        load(body); //just loading the text into the textarea
        
        // asking the component mover to make the customTitleBar (which is a panel) to be the compoment resposible for moving the window/frame
        ComponentMover cm = new ComponentMover(JFrame.class, customTitleBar);
    }
    
    /**
     * Deletes the note
     */
    protected void delete() {
        // asking the parent/manager to delete me :'(
        manager.delete(this);
    }
    
  
    public void load(String body) {
        bodyTextArea.setText(body);
    }
    
    public String getText() {
        return bodyTextArea.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customTitleBar = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        newLabel = new javax.swing.JLabel();
        hide_Button = new javax.swing.JLabel();
        shawall = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 153, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        customTitleBar.setBackground(new java.awt.Color(225, 225, 225));

        closeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        closeLabel.setText("x");
        closeLabel.setToolTipText("Delete Note");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        newLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        newLabel.setText("+");
        newLabel.setToolTipText("Add Note");
        newLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newLabelMouseClicked(evt);
            }
        });

        hide_Button.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        hide_Button.setText("○");
        hide_Button.setToolTipText("HIde Note");
        hide_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide_ButtonMouseClicked(evt);
            }
        });

        shawall.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        shawall.setText("•");
        shawall.setToolTipText("Showall");
        shawall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shawallMouseClicked(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        exitLabel.setText("->]");
        exitLabel.setToolTipText("Exit Label");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(248, 248, 248));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grey", "White", "Yellow", "Green", "Pink" }));
        jComboBox1.setToolTipText("Background Color");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customTitleBarLayout = new javax.swing.GroupLayout(customTitleBar);
        customTitleBar.setLayout(customTitleBarLayout);
        customTitleBarLayout.setHorizontalGroup(
            customTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hide_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shawall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLabel)
                .addGap(8, 8, 8))
        );
        customTitleBarLayout.setVerticalGroup(
            customTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customTitleBarLayout.createSequentialGroup()
                .addGroup(customTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customTitleBarLayout.createSequentialGroup()
                        .addGroup(customTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closeLabel)
                            .addComponent(newLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hide_Button)
                            .addComponent(exitLabel)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(customTitleBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(shawall, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bodyTextArea.setBackground(new java.awt.Color(248, 248, 248));
        bodyTextArea.setColumns(20);
        bodyTextArea.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        bodyTextArea.setRows(5);
        jScrollPane1.setViewportView(bodyTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        this.manager.exit();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void shawallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shawallMouseClicked
        this.manager.show_All();
    }//GEN-LAST:event_shawallMouseClicked

    private void hide_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide_ButtonMouseClicked
        setVisible(false);
        if(this.manager.all_hidden())
        this.manager.exit();
    }//GEN-LAST:event_hide_ButtonMouseClicked

    private void newLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newLabelMouseClicked
        this.manager.newNote("");
    }//GEN-LAST:event_newLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.delete();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
        int x , y, z;
        String s = (String) jComboBox1.getSelectedItem();
        switch (s) {
            case "Grey":
                x = y = z = 248;
                break;
            case "White":
                x = y = z = 255;
                break;
            case "Yellow":
                x = y = 255;
                z = 153;
                break;
            case "Green":
                y =  255;
                x = z = 102;
                break;
            default:
                x = z = 255;
                y = 51;
                break;
        }
       
        
          bodyTextArea.setBackground(new java.awt.Color(x, y, z));
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bodyTextArea;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel customTitleBar;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel hide_Button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newLabel;
    private javax.swing.JLabel shawall;
    // End of variables declaration//GEN-END:variables
}
