/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package all;

import bcrypt.BCrypt;

/**
 *
 * @author Sagar
 */
public class Password {
    
    /**
     * 
     * @param password users password that he entered
     * @param salt a string generated by BCrypt.gensalt() which will be stored on phone.
     * @return hash of the password + salt
     */
    static String hash(String password, String salt){
        String val = BCrypt.hashpw(password, salt);
        return val.substring(29, val.length());
    }
    
    
    /**
     * 
     * @param input  the entered password to check
     * @param hash   the hash saved in database
     * @param salt   the salt saved on phone
     * @return       true if matches else false
     */
    static boolean checkPassword(String input, String hash, String salt){
        boolean i = BCrypt.checkpw(input, salt + hash);
        return i;
    }
    
}
